[project]
name = "calcula-onus"
version = "0.1.1"
description = "Aplicação para o Cálculo de Ônus Tributário por município e por estado dado a outorga de radiofrequência"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "millify>=0.1.1",
    "streamlit>=1.44.0",
]
